[GENERAL]
#Triggers BEAM COSMICS DUALTIMER UNCORRELATED CORRELATED
#Triggers BEAM
#Triggers COSMICS
#Triggers COSMICS DUALTIMER CORRELATED
Triggers ALL
DataQualityLevel 0 #0 evaluates good periods, 1 applies DataQuality cuts
#Database config/run_level_offline_db_2025_full.txt
Database config/tb_2026.txt
#Database config/run_level_offline_db_2022_witherr_patch_RIGHT_periods_lgcorr.txt

[ECAL]
Temp_File config/ECal_Temperature_01.dat
ApplyEfficiencyCorrection  0
EffCorrectionPath /data9Vd1/padme/dimeco/RunIV/TagAndProbeOut/DATAout/ #mind the / when writing the path
AddNoTargetToMC 0
CosmicsPath /data9Vd1/padme/dimeco/RunIV/Cosmics/DATAout/
TPPath /data9Vd1/padme/dimeco/RunIV/TagAndProbeOut/DATAout/
TPWithMMPath /data9Vd1/padme/dimeco/RunIV/TagAndProbeOut/TPwithMM/

[MM]
T0_File config/T0_File.dat
