[GENERAL]
#Triggers BEAM COSMICS DUALTIMER UNCORRELATED CORRELATED
#Triggers BEAM
#Triggers COSMICS
#Triggers COSMICS DUALTIMER CORRELATED
Triggers ALL
DataQualityLevel 0 #0 evaluates good periods, 1 applies DataQuality cuts
<<<<<<< HEAD
=======
Database config/run_level_offline_db_2025.txt
>>>>>>> origin/calibTools

[ECAL]
Temp_File config/ECal_Temperature_01.dat
ApplyEfficiencyCorrection  0
EffCorrectionPath /data9Vd1/padme/dimeco/TagAndProbeOut/DATAout/ #mind the / when writing the path
AddNoTargetToMC 0
<<<<<<< HEAD
=======
CosmicsPath /mnt/l1padme2/dimeco/Cosmics/DATAout/
TPPath /mnt/l1padme2/dimeco/TagAndProbeOut/DATAout/
>>>>>>> origin/calibTools
